name: "build"

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    name: Python ${{ matrix.python-version }} | Clickhouse ${{ matrix.clickhouse-version}} | Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.8
            clickhouse-version: "20.11"
          - python-version: 3.9.6
            clickhouse-version: "20.11"
          - python-version: 3.8
            clickhouse-version: "20.12"
          - python-version: 3.9.6
            clickhouse-version: "20.12"
          - python-version: 3.8
            clickhouse-version: "21"
          - python-version: 3.9.6
            clickhouse-version: "21"
          - python-version: 3.8
            clickhouse-version: "21.1"
          - python-version: 3.9.6
            clickhouse-version: "21.1"

    services:
      clickhouse:
        image: yandex/clickhouse-server:${{ matrix.clickhouse-version}}
        ports:
          - 9000:9000

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: |
        pip install -r dev_requirements.txt

    - name: Run tests
      run: |
        PYTHONPATH="${PYTHONPATH}:dbt" pytest test/integration/clickhouse.dbtspec
